#!/bin/sh
## Symlink .desktop files from Flatpaks into the system application directory
case $1 in -f|--force) ;; *)
    cat >&2 <<EOF
$0: Refusing to continue.

    This script could use some work.  Open it, read the TODO section, and try
    to fix it.  If you don't feel like fixing it, run this script again with
    the \`-f' or \`--force' flag.

EOF
    exit 1
esac

# TODO: Use a better approach
#
# Observations:
# - GNOME is supposed to read .desktop files from every `applications`
#   subdirectory of directories specified in $XDG_DATA_DIRS.
# - $XDG_DATA_DIRS contains /var/lib/flatpak/exports/share and
#   ~/.local/share/flatpak/exports/share.
# - Flatpak should symlink .desktop files into
#   /var/lib/flatpak/exports/share/applications for system flatpaks and into
#   ~/.local/share/flatpak/exports/share/applications for user flatpaks.
# - Beyond /usr/share/applications, there is also /usr/local/share/applications
#   and ~/.local/share/applications.
# - ~/.local/share/applications does not have a corresponding entry in
#   $XDG_DATA_DIRS, but $XDG_DATA_HOME does default to ~/.local/share, and
#   GNOME supposedly looks in ~/.local/share/applications; I need to verify this.
# - If you cannot get the Flatpak-specific `applications' directories to work,
#   then at least try to install them into the generic `applications'
#   directories corresponding to the installation prefix.
# - User edits should go into a copy (not a symlink) of a .desktop file so that
#   edits won't be overwritten by application updates. However, this means that
#   the package-installed .desktop file will be completely ignored, including
#   any updates to the .desktop file across package updates. Unfortunately,
#   user edits must contain an entire .desktop entry and cannot just override
#   individual values, so there is no easy way around this.
#
# References:
# - https://specifications.freedesktop.org/desktop-entry-spec/latest/index.html
# - https://askubuntu.com/questions/610474/can-local-share-applications-override-usr-share-applications
# - https://www.reddit.com/r/Fedora/comments/rqfucu/desktop_files_in_localshareapplications/
# - https://wiki.archlinux.org/title/Desktop_entries
# - https://wiki.gnome.org/Initiatives/Wayland/SessionStart
# - https://unix.stackexchange.com/questions/317282/set-environment-variables-for-gnome-on-wayland-and-bash-on-virtual-terminals-or
# - update-desktop-database(1)
# - desktop-file-install(1)
# - Specific files installed by the flatpak RPM:
#   /etc/profile.d/flatpak.sh
#   /usr/share/flatpak/triggers/*
#   /usr/lib/systemd/system-environment-generators/60-flatpak-system-only
#   /usr/lib/systemd/user-environment-generators/60-flatpak

[ `id -u` -eq 0 ] || exec sudo --preserve-env=XDG_DATA_HOME "$0"
set -x
appdir=/usr/share/applications
cmdstr='test -e "'$appdir'/${1##*/}" || ln -s "$1" '\'$appdir\'
find /var/lib/flatpak/app "$XDG_DATA_HOME"/flatpak/app \
    -path '*/export/share/applications/*' -type f -name '*.desktop' \
    -exec /bin/sh -xc "$cmdstr" "$0" '{}' \;
