#!/bin/sh
progname=`basename "$0"`

# Find temporary directory
: ${TMPDIR='/tmp'}
test -d "$TMPDIR" || {
    echo >&2 "$progname: not a directory: $TMPDIR"
    exit 1
}

# Set up temporary file handling
all=$TMPDIR/$progname-all-$$
enabled=$TMPDIR/$progname-enabled-$$
disabled=$TMPDIR/$progname-disabled-$$
trap "rm -f '$all' '$enabled' '$disabled'" 0 1 2 3 15

# Get a list of all modules
ls -1 "$HOME"/.local/opt | sort > "$all"

# Get a list of enabled modules
sed -e '/^[ 	]*#/d' \
    -e '/^[ 	]*$/d' \
    -e 's/[ 	]*#.*$//' \
    -e 's/^[ 	]*//' \
    "$HOME"/.local/etc/modules | sort -u > "$enabled"

# Get a list of disabled modules
grep -vxf "$enabled" "$all" > "$disabled"

# Get the longest module name
width=`awk '{ if (length > x) x = length } END { print x }' "$all"`

# Dislay all modules, along with "(enabled)" for the enabled ones
awk '{ printf "%-'$width's  (enabled)\n", $1 }' "$enabled" | sort - "$disabled"
