#!/bin/sh
## This command should be run at startup
cat <<EOF
       Stale \$TMPDIR entries: `cleantmp --dry-run | wc -l`
       Emacs auto-save files: `ls -1 "$XDG_CACHE_HOME/emacs/auto-save" | wc -l`
              Vim swap files: `ls -1 "$XDG_CACHE_HOME/vim/swap" | wc -l`
        Uncommitted dotfiles: `git -C "$HOME" status --porcelain | wc -l`
 Uncommitted reference files: `git -C "$HOME/ref" status --porcelain | wc -l`
EOF
