DISPLAY=:0.0
XENVIRONMENT=$XDG_CONFIG_HOME/X11/Xdefaults
XINITRC=$XDG_CONFIG_HOME/X11/xinitrc
XSERVERRC=$XDG_CONFIG_HOME/X11/xserverrc
XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority
LIBGL_ALWAYS_INDIRECT=1
export DISPLAY XENVIRONMENT XINITRC XSERVERRC XAUTHORITY LIBGL_ALWAYS_INDIRECT
