#!/bin/sh
## Run a git operation in every subdirectory with a git repo

# XXX: Hack to get to the cwd of the parent process
test "X$GIT_PREFIX" = X || cd -- "$GIT_PREFIX"

# Only return 0 if *everything* succeeds
rc=0

# Output a nice header to separate this command from the others
cat <<EOF
-------------------------------------------------------------------------------
GIT-REPOS COMMAND STARTED: `date`
-------------------------------------------------------------------------------
EOF

# For each subdirectory that is the toplevel of a git worktree (without
# traversing into subprojects found within those worktrees)
find . -name .git \( -path ./.git -prune -o -print \) |
sed -e 's|^\./\(.*\)/\.git$|\1|' |
awk 'index($0, x "/") == 1 { next } { print x = $0 }' |
while read repo
do
    # This handles both repo directories and gitlink files
    git rev-parse --resolve-git-dir "$repo/.git" >/dev/null 2>&1 || continue
    echo >&2 "=== $repo ==="

    # Navigate to that directory and do something!
    (
        set -e
        cd "$repo"
        git "$@"
    ) || rc=1
done
exit $rc
