#!/bin/sh
## Print all parent IDs of a Docker object
## Requires: docker jq

id=$1
test "X$id" = X && {
    echo >&2 "Usage: docker parents [ID | NAME]"
    exit 1
}

while :
do
    # Find cryptographic hash of parent
    sum=`docker inspect "$id" | jq '.[0].Parent' | sed -e '/^""$/d' -e 's/^.*://' -e 's/"$//'`

    # If it's empty, we've reached the root ancestor
    test "X$sum" = X && exit 0

    # Otherwise, let's trim the hash to 12 characters to make it an ID
    id=`echo "$sum" | cut -c1-12`

    # Print the ID
    echo $id
done
