#!/bin/sh
## Requires: tree

# Ignore this wrapper script
bindir=`pwd | sed 's#\(/stow-dotfiles\)/.*#\1#'`/.bin
tree=`which -a tree | grep -vxF "$bindir/tree" | head -n 1`

# Exit if there is no other tree executable on $PATH
[ "X$tree" = X ] && {
    echo >&2 'command not found: tree'
    exit 1
}

# Output a directory tree with directories first, showing hidden files
[ -t 0 ] && set -- -C ${1+"$@"}
exec $tree --dirsfirst -a ${1+"$@"}
