# -----------------------------------------------------------------------------
# K9s Kiss Skin
# Author: [@beejeebus](justin.p.randell@gmail.com)
# Customized by @eeowaa
# -----------------------------------------------------------------------------

# Styles...

# Skin...
k9s:
  body:
    fgColor: black
    bgColor: default
    logoColor: default
  prompt:
    fgColor: black
    bgColor: default
    suggestColor: default
  info:
    fgColor: default
    sectionColor: default
  dialog:
    fgColor: default
    bgColor: default
    buttonFgColor: white
    buttonBgColor: black
    buttonFocusFgColor: white
    buttonFocusBgColor: black
    labelFgColor: black
    fieldFgColor: blue
  frame:
    border:
      fgColor: default
      focusColor: default
    menu:
      fgColor: default
      keyColor: default
      numKeyColor: default
    crumbs:
      fgColor: default
      bgColor: black
      activeColor: black
    status:
      newColor: default
      modifyColor: default
      addColor: default
      errorColor: default
      highlightColor: default
      killColor: default
      completedColor: default
    title:
      fgColor: default
      bgColor: default
      highlightColor: default
      counterColor: default
      filterColor: default
  views:
    table:
      fgColor: default
      bgColor: default
      cursorFgColor: default
      cursorBfColor: default
      header:
        fgColor: default
        bgColor: default
        sorterColor: default
    yaml:
      keyColor: default
      colonColor: default
      valueColor: black
    logs:
      fgColor: default
      bgColor: default
      indicator:
        fgColor: default
        bgColor: default
        toggleOnColor: default
        toggleOffColor: default
